version: '3.3'
services:
  dns_server:
    image: insternetsystemsconsortium/bind9:9.18
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      dns_network:
          ipv4_address: 172.20.0.2
    volumes:
      - ./bind-config:/etc/bind

  dns_client:
    image: alpine:latest
    container_name: alpine-client
    command: sh -c "apk update && apk add bind-tools && sleep infinity"
    networks:
      - dns_network

networks:
   dns_network:
     driver: bridge
     ipam:
       config:
         - subnet: 172.20.0.0/24